apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticketing
  template:
    metadata:
      labels:
        app: ticketing
    spec:
      containers:
      - name: ticketing
        image: ticketing-service:latest
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-service
spec:
  selector:
    app: ticketing
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
